# Only placeholders used in metadata/resource templates must exist in loader-common.gradle expandProps.

# Project
version=1.1.0
group=io.github.vv22003.buttonfix
java_version=21

# Common
minecraft_version=1.21.8
mod_name=Button Fix
mod_author=vv22003
mod_id=buttonfix
license=LGPL-3.0-or-later
description=A small client-side mod that fixes widget focus issues in any in-game GUI.

# Fabric
# https://fabricmc.net/develop/
fabric_loader_version=0.19.2
fabric_api_version=0.136.1+1.21.8
fabric_minecraft_version_range=>=1.19.4 <=1.21.11
loom_version=1.10-SNAPSHOT

# Forge
resource_pack_format=15
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_loader_version=58.1.0
forge_loader_version_range=[45,61]
forge_minecraft_version_range=[1.19.4,1.21.11]
# https://files.minecraftforge.net/net/minecraftforge/gradle/ForgeGradle/
forgegradle_version=6.0.53

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_loader_version=21.8.35
neoforge_loader_version_range=[21,)
neoforge_minecraft_version_range=[1.20.1,1.21.11]
# https://projects.neoforged.net/neoforged/moddevgradle
moddevgradle_version=2.0.141

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true