plugins {
    id "loader-common"
    id "net.minecraftforge.gradle" version "${forgegradle_version}"
}

minecraft {
    mappings channel: "official", version: "${minecraft_version}"

    runs {
        client {
            workingDirectory file("runs/client")
        }
    }
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = "Minecraft"
                url = uri("https://libraries.minecraft.net")
            }
        }
        filter { includeModule("org.lwjgl", "lwjgl-freetype") }
    }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_loader_version}"
    implementation("net.sf.jopt-simple:jopt-simple:5.0.4") { version { strictly "5.0.4" } }
}

sourceSets.main.output.resourcesDir = layout.buildDirectory.dir("sourcesSets/main")
sourceSets.main.java.destinationDirectory = layout.buildDirectory.dir("sourcesSets/main")