plugins {
    id "loader-common"
    id "net.neoforged.moddev" version "${moddevgradle_version}"
}

neoForge {
    version = neoforge_loader_version
    runs {
        client {
            client()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}